---
title: "Mountain Pine Beetle Climatic Suitability Maps"
author: "Alex M. Chubaty, Barry J. Cooke, Eliot J. B. McIntire"
date: "October 26, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(magrittr)

maps.dir <- '~/Documents/Data/shared/MPB/climate'
if (!file.exists(maps.dir)) stop("maps dir does not exist.")

download = FALSE
```

## Data source

Maps were produced in BioSim (need info!).

They were uploaded to and retrieved from the [NoFC FTP site](ftp://ftp.nofc.cfs.nrcan.gc.ca/uploads/MPB) on 26 October 2016.

```{r download-data}
if (download) {
  library(RCurl)
  
  ## Get files of size zero
  file.size <- function(file) {
    return(file.info(file)$size)
  }
  
  eol <- ifelse(Sys.info()[["sysname"]] == "Windows", "\r\n", "\n")
  
  ## Define the ftp address (NOTE this address is temporary)
  ftp.site <- 'ftp://ftp.nofc.cfs.nrcan.gc.ca/uploads/MPB/'
  
  ftp.files <- getURL(ftp.site, ftp.use.epsv = FALSE, dirlistonly = TRUE) %>%
    strsplit(split = eol) %>% 
    unlist()
  
  for (f in ftp.files) {
    f.local <- file.path(maps.dir, f)
    f.ftp <- file.path(ftp.site, f)
    
    if (!file.exists(f.local)) {
      try(download.file(f.ftp, f.local))
    } else {
      if (file.size(f.local) == 0) {
        try(download.file(f.ftp, f.local))
      }
    }
  }
}
```

## Plot maps

