---
title: "mpbRedTopMassAttacks"
author:
  - "Alex M. Chubaty"
  - "Barry J. Cooke"
  - "Eliot J. B. McIntire"
date: "April 24, 2017"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
bibliography:
  - ../../bibliography.bib
---

## Summary

This module imports the raw MPB red top attack data from AB and BC over several years.
@Cooke:2017fem describes the methodology by which MPB attack data for AB (derived from spatial points) and BC (derived from polygons) have been rasterized and merged into a single `RasterLayer`:

> To provide an unbiased perspective on MPB damage in the two provinces, the two data sets were rasterized to a common resolution, allowing impact to be expressed in common units (hectares attacked per 4 km2 cell).
> For BC data, raster cells were weighted according to polygon-wide average infestation rates and areas calculated from the proportion of a polygon infested within each raster cell, assuming an average stem density of 1125 mature stems per hectare, which is typical for beetle-prone lodgepole pine stands (Whitehead and Russo, 2005).
> Data were weighted and calculated for each year in the sequence, and then summed. For Alberta data, the number of attacked trees per point attack cluster was determined from provincial government records, based on a ground survey, and summed across years within each 4 km2 raster cell.

**NOTE:** We produced finer-resolusion rasters (250m x 250m) to match the resolution of the kNN pine maps.

**NOTE:** currently, only the data up to and including 2011 are being used, as more recent data for BC have not yet been acquired (we have AB aerial survey data up to and including 2016).
