---
title: "MPB dynamics and spread"
author: "Alex M. Chubaty"
date: "January 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (Sys.info()[["user"]] == "achubaty") {
  library(SpaDES, .Library.dev)
  stopifnot(packageVersion("SpaDES", .Library.dev) >= "1.3.1.9019")
} else {
  library(SpaDES)
  stopifnot(packageVersion("SpaDES") >= "1.3.1.9019")
}
library(raster)

setPaths(modulePath = "~/GitHub/MPB/SpaDES/modules")
dev.useRSGD(FALSE)

## load CRS for the boreal raster
load(file.path(getOption("spades.modulePath"), "mpbRandomLandscapes", "data", "west.boreal.RData")) ## loads studyArea object (spdf)
crs.boreal <- CRS(proj4string(studyArea))
rm(studyArea)

## define (small) study area for development
nx <- ny <- 2000
studyArea <- raster::raster(nrows = ny, ncols = nx,
                            xmn = -245643, xmx = -213643,
                            ymn = 5615173, ymx = 5637173,
                            crs = crs.boreal)

times <- list(start = 2011, end = 2020)
params <- list(
  ##
  mpbClimate = list(suitabilityIndex = "G") # Can be "G", "S", "L", "R"
)
modules <- list(#"mpbRandomLandscapes",
                "mpbPine", "mpbClimate",  ## use EITHER mpbRandomLandscapes OR mpbPine/mpbClimate
                #"mpbMassAttacks",
                #"mpbRedTopDispersal",
                "mpbGrowth_B79forced")
objects <- list(studyArea = studyArea)

MPB <- simInit(times = times, params = params, modules = modules)#, objects = objects)

MPB2 <- spades(Copy(MPB), debug = TRUE)
```

## Simulation diagrams

```{r sim-diagrams}
moduleDiagram(MPB2)
objectDiagram(MPB2)
eventDiagram(MPB2)
```
