---
title: "Pine maps"
author: "Alex Chubaty"
date: "November 24, 2017"
output: pdf_document
bibliography: bibliography.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
## determine OS and whether we are on a CFS machine
._CFS_. <- grepl("W-VIC", Sys.info()[["nodename"]])
._OS_. <- Sys.info()[["sysname"]]
._USER_. <- Sys.info()[["user"]]

## set R and knitr options
if (isTRUE(._CFS_.)) {
  options(repos = c(CRAN = "https://cran.rstudio.com/",
                    NRCRAN = "http://132.156.148.172"))
} else {
  options(repos = c(CRAN = "https://cran.rstudio.com/"))
}

knitr::opts_chunk$set(cache = TRUE, echo = FALSE, eval = TRUE)

## load and attach required packages
library(httr)
library(magrittr)
library(raster)
library(rasterVis)

if (!require(amc) || packageVersion("amc") < "0.1.2.9000") {
  devtools::install_github("achubaty/amc@development")
}

# set work dirs based on computer used
if (._USER_. == "achubaty") {
  if (._OS_. == "Darwin") {
    maps.dir <- "~/Documents/shared"
  } else if (._OS_. == "Linux") {
    if (isTRUE(._CFS_.)) {
      maps.dir <- "/mnt/A105388/shared/data"
    } else {
      maps.dir <- "~/Documents/Data/shared"
    }
  } else if (._OS_. == "Windows") {
    maps.dir <- "//W-VIC-A105388/shared/data"
  } else {
    stop("Which operating system are you using?")
  }
}

download.data <- FALSE
kNN.dir <- file.path(maps.dir, "kNN")
pineMap.dir <- file.path(maps.dir, "Yemshanov_pine_map")
```

## Yemshanov pine map

From @Yemshanov:2012ea.

```{r yemshanov-download}
if (isTRUE(download.data)) {
  if (!dir.exists(pineMap.dir)) {
    dir.create(pineMap.dir)
  }
  
  # the paper describing the data set is here (behind a paywall):
  #  http://link.springer.com/article/10.1007/s10661-011-2293-2
  #
  # but I have made it available via Dropbox:
  #  https://www.dropbox.com/s/uh7g570gns1dpn3/yemshanov.etal_2012.pdf
  #
  
  ## download files
  eol <- ifelse(os == "windows", "\r\n", "\n")
  url <- "ftp://ftp.nofc.cfs.nrcan.gc.ca/downloads/Cooke/Yemshanov_pine_map/" ## temporary
  paper_url <- "https://www.dropbox.com/s/uh7g570gns1dpn3/yemshanov.etal_2012.pdf?dl=1"
  paper <- basename(paper_url)
  fileNames <- unlist(strsplit(getURL(url, dirlistonly = TRUE), split = eol))
  lapply(fileNames, function(f) {
    if (!file.exists(file.path(pineMap.dir, f))) {
      download.file(paste0(url, f), destfile = file.path(pineMap.dir, f))
    }
  })
  if (!file.exists(file.path(pineMap.dir, paper))) {
     download.file(paper_url, destfile = file.path(pineMap.dir, paper))
  }
}
```

Plotting using `raster` package looks OK but not great:

```{r yemshanov-plot}
## load the map
pineMap_file <- dir(pineMap.dir, pattern = "[.]flt$", full.names = TRUE)
pineMap_raster <- raster(pineMap_file)

## plot the map
# if the plot looks messed up it's likely due to corrupted download
plot(pineMap_raster)
```

Using `rasterVis` package, it's much nicer:

```{r yemshanov-plot-rasterVis}
myTheme <- rasterTheme(region = brewer.pal('Greens', n = 9)[3:9])
levelplot(pineMap_raster, margin = list(median), maxpixels = 1e6, par.settings = myTheme)
```

## Beaudoin *et al.* kNN pine maps

From @Beaudoin:2014cf.

### Download

```{r kNN-download, eval = FALSE}
if (isTRUE(download.data)) {
  if (!dir.exists(kNN.dir)) {
    dir.create(kNN.dir)
  }
  
  url <- "http://tree.nfis.org/"
  docFiles <- c("NFI_and_kNN_Mapping_20160628.docx",
                "FR_NFI_and_kNN_Mapping_20160628.docx",
                "cjfr-2013-0401suppl.pdf")
  dataFiles <- c("kNN-Species.tar", ## percent pine layers
                 "kNN-StructureStandVolume.tar") ## age & total volume layers

  dl.data(paste0(url, c(docFiles, dataFiles)), kNN.dir)

  ## percent pine layers
  destDir <- file.path(kNN.dir, "kNN-Species")
  if (!dir.exists(destDir)) dir.create(destDir)
  
  untar(file.path(kNN.dir, dataFiles[1]),
        files = c("NFI_MODIS250m_kNN_Species_Pinu_Ban_v0.zip",
                  "NFI_MODIS250m_kNN_Species_Pinu_Con_v0.zip"),
        exdir = path.expand(destDir))
  
  zipFile <- file.path(destDir, "NFI_MODIS250m_kNN_Species_Pinu_Ban_v0.zip")
  destDir2 <- file.path(tools::file_path_sans_ext(zipFile))
  unzip(zipFile, exdir = destDir2)
  
  zipFile <- file.path(destDir, "NFI_MODIS250m_kNN_Species_Pinu_Con_v0.zip")
  destDir2 <- file.path(tools::file_path_sans_ext(zipFile))
  unzip(zipFile, exdir = destDir2)
  
  ## age & total volume layers
  destDir <- file.path(kNN.dir, "kNN-StructureStandVolume")
  if (!dir.exists(destDir)) dir.create(destDir)
  
  untar(file.path(kNN.dir, dataFiles[2]),
        files = c("NFI_MODIS250m_kNN_Structure_Stand_Age_v0.zip",
                  "NFI_MODIS250m_kNN_Structure_Volume_Total_v0.zip"),
        exdir = path.expand(destDir))
  
  zipFile <- file.path(destDir, "NFI_MODIS250m_kNN_Structure_Stand_Age_v0.zip")
  destDir2 <- file.path(tools::file_path_sans_ext(zipFile))
  unzip(zipFile, exdir = destDir2)
  
  zipFile <- file.path(destDir, "NFI_MODIS250m_kNN_Structure_Volume_Total_v0.zip")
  destDir2 <- file.path(tools::file_path_sans_ext(zipFile))
  unzip(zipFile, exdir = destDir2)
}
```

### Percent pine (%)

```{r knn-raster-percentPine}
files <- file.path(maps.dir, ifelse(._CFS_., "kNN/original", "kNN"), "kNN-Species",
                   c("NFI_MODIS250m_kNN_Species_Pinu_Ban_v0",
                     "NFI_MODIS250m_kNN_Species_Pinu_Con_v0"),
                   c("NFI_MODIS250m_kNN_Species_Pinu_Ban_v0.tif",
                     "NFI_MODIS250m_kNN_Species_Pinu_Con_v0.tif"))
stopifnot(file.exists(files))

kNN_percentPine <- stack(x = files) %>% setNames(c("Jack_Pine", "Lodgepole_Pine"))

save(kNN_percentPine, file = file.path(kNN.dir, "kNN_percentPine.Rdata"))
writeRaster(kNN_percentPine, filename = file.path(kNN.dir, "kNN_percentPine.tif"), overwrite = TRUE)
file.copy(file.path(kNN.dir, "kNN_percentPine.Rdata"),
          "~/Documents/GitHub/MPB/SpaDES/modules/mpbPine/data/kNN_pine_map.tif",
          overwrite = TRUE)
```

```{r knn-plot-percentPine}
## plot it
plot(kNN_percentPine)

## even better with rasterVis
myTheme <- rasterTheme(region = brewer.pal("Greens", n = 9))
levelplot(kNN_percentPine, margin = list(median), maxpixels = 1e6, par.settings = myTheme)
```

### Pine volume (m^3/ha)

```{r knn-raster-volumePine}
f <- file.path(maps.dir, ifelse(._CFS_., "kNN/original", "kNN"),
               "kNN-StructureStandVolume",
               "NFI_MODIS250m_kNN_Structure_Volume_Total_v0",
               "NFI_MODIS250m_kNN_Structure_Volume_Total_v0.tif")
stopifnot(file.exists(f))

kNN_volumeTotal <- raster(f) %>% setNames("Volume_Total")
save(kNN_volumeTotal, file = file.path(kNN.dir, "kNN_volumeTotal.Rdata"))

kNN_volumePine <- kNN_percentPine
kNN_volumePine[[1]] <- kNN_percentPine[[1]] * kNN_volumeTotal / 100 # Jack_Pine
kNN_volumePine[[2]] <- kNN_percentPine[[2]] * kNN_volumeTotal / 100 # Lodgepole_Pine
names(kNN_volumePine) <- names(kNN_percentPine)
save(kNN_volumePine, file = file.path(kNN.dir, "kNN_volumePine.Rdata"))
writeRaster(kNN_volumePine, filename = file.path(kNN.dir, "kNN_volumePine.tif"))
```

```{r knn-plot-volumePine}
## plot it
plot(kNN_volumePine_map)

## even better with rasterVis
myTheme <- rasterTheme(region = brewer.pal("Greens", n = 9))
#pdf(file.path("pine-maps", "pineVolume.pdf"), width = 12, height = 6)
levelplot(kNN_volumePine, margin = list(median), maxpixels = 1e6, par.settings = myTheme)
#dev.off()
```

### Stand age (a)

```{r knn-raster-standAge}
f <- file.path(maps.dir, ifelse(._CFS_., "kNN/original", "kNN"),
               "kNN-StructureStandVolume",
               "NFI_MODIS250m_kNN_Structure_Stand_Age_v0",
               "NFI_MODIS250m_kNN_Structure_Stand_Age_v0.tif")
stopifnot(file.exists(f))

kNN_standAge <- raster(f) %>% setNames("Stand_Age")
save(kNN_standAge, file = file.path(kNN.dir, "kNN_standAge.Rdata"))
```

```{r knn-plot-standAge}
## plot it
plot(kNN_standAge)

## even better with rasterVis
myTheme2 <- rasterTheme(region = brewer.pal("Blues", n = 9))
levelplot(kNN_standAge, margin = list(median), maxpixels = 1e6, par.settings = myTheme2)
```

### Other data sources

```
Kyle Lochhead; Valerie LeMay; Gary Bull; Olaf Schwab; James Halperin, 2017-07-26, "Multivariate maps of forest attributes for management units in Canada's boreal forest", http://hdl.handle.net/11272/10515 V2 [Version]
```

# References

<!-- automatically generated using bibliography.bib -->